config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'apply', to: 'pages#apply', as: 'apply'
  get 'start', to: 'pages#start', as: 'start'
  get 'thanks', to: 'pages#thanks', as: 'thanks'
  get 'magic_link', to: 'pages#magic_link', as: 'magic_link'

  devise_for :users
  get 'logout', to: 'pages#logout', as: 'logout'

  get 'dashboard', to: 'dashboard#index'


  resources :user_submissions, only: [:create]
  resources :projects, only: [:update]
  resources :subscribers, only: [:create, :destroy]
  resources :stakeholder_updates, only: [:new, :create, :show, :update, :edit]
  resources :updates, only: [:show]

  resources :subscribe, only: [:index]
  # resources :dashboard, only: [:index]
  resources :account, only: [:index, :update]
  resources :billing_portal, only: [:create]
  match '/billing_portal' => 'billing_portal#create', via: [:get]
  match '/cancel' => 'billing_portal#destroy', via: [:get]

  # static pages
  pages = %w(
    privacy terms
  )

  pages.each do |page|
    get "/#{page}", to: "pages##{page}", as: "#{page.gsub('-', '_')}"
  end

  # admin panels
  authenticated :user, -> user { user.admin? } do
    namespace :admin do
      get '/', to: 'pages#dashboard'
      resources :user_submissions, only: [:update]
    end
  end
  # authenticated :user, -> user { user.admin? } do
  #   namespace :admin do
  #     resources :dashboard, only: [:index]
  #     resources :impersonations, only: [:new]
  #     resources :users, only: [:edit, :update, :destroy]
  #   end
  #
  #   # convenience helper
  #   get 'admin', to: 'admin/dashboard#index'
  # end
end

app/views/admin/pages/dashboard.html.erb
<%= render partial: "shared/heading", locals: { title: 'Admin Panel', tagline: 'Accept or Reject' } %>


<div class="px-6 lg:px-8">

  <div class="mt-8 flow-root">
    <div class="-my-2 -mx-6 overflow-x-auto lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300">
          <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-6 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Applicant Name</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Plan</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Email</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Website</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Role</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Newsletter</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Status</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200 bg-white">
            <% @user_submissions.each do |user_submission| %>
              <tr>
                <td class="whitespace-nowrap px-3 py-4 text-xs text-gray-500"><%= user_submission.name %></td>
                <td class="whitespace-nowrap px-3 py-4 text-xs text-gray-500"><%= user_submission.plan_name %></td>
                <td class="whitespace-nowrap px-3 py-4 text-xs text-gray-500"><%= user_submission.email %></td>
                <td class="whitespace-nowrap px-3 py-4 text-xs text-gray-500"><%= user_submission.website %></td>
                <td class="whitespace-nowrap px-3 py-4 text-xs text-gray-500"><%= user_submission.job_role %></td>
                <td class="max-w-s px-3 py-4 text-xs text-gray-500"><%= user_submission.text %></td>
                <td class="  py-4 text-xs text-gray-500">
                  <div>
                    <%= form_for user_submission, url: admin_user_submission_path(user_submission) do |f| %>
                    <select id="user_submission_status" name="user_submission[status]" class="mt-1 block w-full rounded-md border-gray-300 py-2 pl-3 pr-10 text-base focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm">
                      <option <%= 'selected' if user_submission.status.nil? %>>Pending</option>
                      <option <%= 'selected' if user_submission.status == 'Accepted' %>>Accepted</option>
                      <option <%= 'selected' if user_submission.status == 'Rejected' %>>Rejected</option>
                    </select>
                    <%= f.submit 'Update', class: 'inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2'%>
                    <% end %>
                  </div>
                </td>
              </tr>
            <% end %>


            <!-- More people... -->
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>