config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'apply', to: 'pages#apply', as: 'apply'
  get 'start', to: 'pages#start', as: 'start'
  get 'thanks', to: 'pages#thanks', as: 'thanks'
  get 'magic_link', to: 'pages#magic_link', as: 'magic_link'

  devise_for :users
  get 'logout', to: 'pages#logout', as: 'logout'

  get 'dashboard', to: 'dashboard#index'


  resources :user_submissions, only: [:create]
  resources :projects, only: [:update]
  resources :subscribers, only: [:create, :destroy]
  resources :stakeholder_updates, only: [:new, :create, :show, :update, :edit]
  resources :updates, only: [:show]

  resources :subscribe, only: [:index]
  # resources :dashboard, only: [:index]
  resources :account, only: [:index, :update]
  resources :billing_portal, only: [:create]
  match '/billing_portal' => 'billing_portal#create', via: [:get]
  match '/cancel' => 'billing_portal#destroy', via: [:get]

  # static pages
  pages = %w(
    privacy terms
  )

  pages.each do |page|
    get "/#{page}", to: "pages##{page}", as: "#{page.gsub('-', '_')}"
  end

  # admin panels
  authenticated :user, -> user { user.admin? } do
    namespace :admin do
      get '/', to: 'pages#dashboard'
      resources :user_submissions, only: [:update]
    end
  end
  # authenticated :user, -> user { user.admin? } do
  #   namespace :admin do
  #     resources :dashboard, only: [:index]
  #     resources :impersonations, only: [:new]
  #     resources :users, only: [:edit, :update, :destroy]
  #   end
  #
  #   # convenience helper
  #   get 'admin', to: 'admin/dashboard#index'
  # end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all.order(created_at: :desc)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  # before_action :authenticate_user!
  before_action :authenticate_user!
  before_action :maybe_subscribe

  def index
    @project = current_user.default_project
    @other_projects = Project.except(@project).ready
  end

  private





end

app/views/dashboard/index.html.erb
<%= render partial: "shared/heading", locals: { title: 'Dashboard', tagline: 'Browse newsletters and submit your own' } %>


<!-- Dashbosrd box -->
<div class="border border-black border-2 p-5 max-w-xl mx-auto mb-20">
  <div class="flex">
    <div class="basis-1/2">
      <div class="flex gap-x-2">
        <div class="basis-1/6">
          <a href="https://placeholder.com"><img src="https://logo.clearbit.com/<%= @project.website %>"></a>
        </div>
        <div class="basis-5/6">
          <p class="text-lg"><%= @project.title %></p>
          <p class="text-sm"><%= @project.description %></p>
        </div>
      </div>
    </div>
    <div class="basis-1/2 text-right">
      <p><%= @project.subscribers.count %> subscribers</p>
      <p><a class="underline"href="/stakeholder_updates/new">Write update</a> <% unless current_user.stakeholder_updates.count.zero? %>
          | <a href="<%= stakeholder_update_path(current_user.stakeholder_updates.last) %>" class="text-brand-orange underline">View last</a>
        <% end %></p>

    </div>
  </div>
</div>

<!-- newsletter space -->

<div class=" p-5 max-w-xl mx-auto mb-20 space-y-4">
<% @other_projects.each do |proj|%>
  <div class="flex border border-dashed border-2 p-2">
    <div class="basis-1/2">
      <div class="flex gap-x-2">
        <div class="basis-1/6">
          <a href="https://placeholder.com"><img src="https://logo.clearbit.com/<%= proj.website %>"></a>
        </div>
        <div class="basis-5/6">
          <p class="text-lg"><%= proj.title %></p>
          <p class="text-xs"><%= proj.description %> (<%= proj.website %>)</p>
        </div>
      </div>
    </div>
    <div class="basis-1/2 text-right">
      <div class="relative flex items-start py-4">
        <div class="min-w-0 flex-1 text-sm">
              <label for="<%= proj.id %>_subscribed_status" class="font-medium text-gray-700">Subscribed?</label>
        </div>
            <div class="ml-3 flex h-5 items-center">
              <% subscriber = Subscriber.find_by(user_id: current_user.id, project_id: proj.id) %>
              <input onchange="checkboxChanged(this)" <%= 'checked' if subscriber %> data-subscriber-id="<%= subscriber.try(:id) %>" data-project-id="<%= proj.id %>" id="<%= proj.id %>_subscribed_status" aria-describedby="subscribed" name="subscribed" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-brand-orange focus:ring-brand-orange-dark">
            </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

<script type="text/javascript">
  function checkboxChanged(checkbox) {
    let projectId = checkbox.dataset.projectId;

    if (checkbox.checked) {
      createSubscription(projectId, checkbox);
    } else {
      let subscriberId = checkbox.dataset.subscriberId;
      deleteSubscription(projectId, subscriberId);
    }
  }

  function createSubscription(projectId, checkbox) {
    $.ajax({
      url: '/subscribers',
      method: 'POST',
      data: { subscriber: { project_id: projectId } },
      success: function(data){
        if (data.success) {
          checkbox.dataset.subscriberId = data.subscriber_id;
        } else {
          checkbox.checked = false; // revert user's intended behavior in UI
          alert(data.error);
        }
      }
    })
  }

  function deleteSubscription(projectId, subscriberId) {
    $.ajax({
      url: '/subscribers/' + subscriberId,
      method: 'DELETE',
      data: { subscriber: { project_id: projectId } },
      success: function(data){
        console.log('subscriber deleted');
      }
    })
  }
</script>